### Listar os agendamentos 
  GET https://localhost:5001/api/agendamento/listar


### Buscar os agendamentos
  GET https://localhost:5001/api/agendamento/buscar/amanda


### Cadastrar novos agendamentos
  POST https://localhost:5001/api/agendamento/cadastrar
  Content-Type: application/json

  {
    "Cliente": "Jose",
    "Artista": "Joses",
    "Produto": "Tatuagem de estrela no ombro",
    "Data": "12/09/2022",
    "Horario" "12:30"
  }

### Deletar um agendamento
  DELETE  https://localhost:5001/api/agendamento/deletar/amanda

  
### Alterar um agendamento
  PATCH  https://localhost:5001/api/agendamento/alterar
  Content-Type: application/json

#   {
#     "nome" : "joaozin",
#     "cpf" : "amanda"
#   }

  //confirmar a forma de buscar o agendamento, data, nome do artista ou ID